// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: commons/protos/email.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmailServices_SendEmail_FullMethodName = "/protos.EmailServices/SendEmail"
)

// EmailServicesClient is the client API for EmailServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailServicesClient interface {
	SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error)
}

type emailServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailServicesClient(cc grpc.ClientConnInterface) EmailServicesClient {
	return &emailServicesClient{cc}
}

func (c *emailServicesClient) SendEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*EmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, EmailServices_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServicesServer is the server API for EmailServices service.
// All implementations must embed UnimplementedEmailServicesServer
// for forward compatibility.
type EmailServicesServer interface {
	SendEmail(context.Context, *EmailRequest) (*EmailResponse, error)
	mustEmbedUnimplementedEmailServicesServer()
}

// UnimplementedEmailServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailServicesServer struct{}

func (UnimplementedEmailServicesServer) SendEmail(context.Context, *EmailRequest) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedEmailServicesServer) mustEmbedUnimplementedEmailServicesServer() {}
func (UnimplementedEmailServicesServer) testEmbeddedByValue()                       {}

// UnsafeEmailServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailServicesServer will
// result in compilation errors.
type UnsafeEmailServicesServer interface {
	mustEmbedUnimplementedEmailServicesServer()
}

func RegisterEmailServicesServer(s grpc.ServiceRegistrar, srv EmailServicesServer) {
	// If the following call pancis, it indicates UnimplementedEmailServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailServices_ServiceDesc, srv)
}

func _EmailServices_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServicesServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailServices_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServicesServer).SendEmail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailServices_ServiceDesc is the grpc.ServiceDesc for EmailServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.EmailServices",
	HandlerType: (*EmailServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _EmailServices_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commons/protos/email.proto",
}
